# OpenCV 사용하기

## opencv 설치하기
* Anaconda Prompt나 명령 프롬프트(cmd)를 실행합니다.
* 가상환경을 사용하는 경우 conda activate 가상환경이름으로 가상환경을 활성화합니다.
* ```pip install opencv-python``` 명령어로 설치합니다.
* ```jupyter notebook``` 명령어로 주피터 노트북을 실행합니다.

In [2]:
# OpenCV를 import 하고 버전을 확인합니다.
import cv2
cv2.__version__

'4.9.0'

## 도형 그리기

### OpenCV 그리기 기초
* numpy를 사용해서 그림 그릴 공간을 정합니다.
* imshow로 이미지를 창에 보여줍니다.
* waitKey로 지정된 시간 동안 사용자가 키를 입력할 때까지 기다립니다.
    * 기준은 밀리초입니다.
        * 1000밀리초 = 1초
    * waitKey(0)이면 계속 기다립니다.
    * waitKey(5000)이면 5초 기다리고 그 아래 있는 코드가 실행됩니다.
    * destroyAllWindows로 창을 닫습니다.
* opencv에서 RGB가 아니라 BGR 순입니다.

In [3]:
import numpy as np

In [8]:
# 세로 400 X 가로 400에 RGB(3채널)을 사용하는 공간을 만들겠습니다.
# 세로부터 시작합니다.
# zeros를 데이터를 0으로 채웁니다.
img = np.zeros((400,400,3), dtype=np.uint8)
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [7]:
# 프로그램을 시작하면 작업 표시줄에 아이콘이 하나 생깁니다.
# 이 아이콘이 클릭하면 그림이 나옵니다.
# 0,0,0이면 검은색입니다.
cv2.imshow('img', img) # 'img'는 창 이름입니다.
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 255, 255, 255이면 하얀색입니다.
img[:] = 255 # 데이터를 모두 255로 바꿉니다.
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# OpenCV는 BGR 순입니다.
# 배경색을 파란색으로 바꿔보겠습니다.
img[:] = (255,0,0)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### 일부 영역 그리기
* OpenCV에서 왼쪽 위가 기준입니다.
    * (0,0)입니다.
* 오른쪽으로 갈수록 x좌푯값이 커집니다.
* 아래로 갈수록 y좌푯값이 커집니다. 

In [17]:
# 일단 배경색을 검은색으로 하겠습니다.
img[:] = (0,0,0)
# img 변수에 슬라이싱을 해서 영역을 정합니다.
# 왼쪽 위가 기준입니다.
img[0:100, 0:100] = (255,255,255)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### 직선 그리기
* 선의 종류가 있습니다.
* cv2.LINE_8 : 대각선을 포함한 8 방향으로 연결된 선(기본값)
* cv2.LINE_AA : 부드러운 선(anti-aliasing)
* line(이미지객체, (시작x, 시작y), (끝x, 끝y), 색깔, 굵기, 선 종류)로 그립니다.
    * 선 종류를 넣지 않으면 기본값인 cv2.LINE_8이 됩니다. 

In [20]:
img[:] = (0,0,0)
cv2.line(img, (0,0), (200,200), (0,0,255), 3, cv2.LINE_AA)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### 원
* circle(이미지객체, (중심점x, 중심점y), 반지름, 색깔, 굵기, 선 종류)로 그립니다.
* circle(이미지객체, (중심점x, 중심점y), 반지름, 색깔, cv2.FILLED, 선 종류)로 색칠한 원을 그립니다.

In [23]:
# 다시 검은색으로 배경색을 정합니다.
img[:] = (0,0,0)
cv2.circle(img, (200,200), 50, (0,0,255), 5, cv2.LINE_AA)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
img[:] = (0,0,0)
cv2.circle(img, (200,200), 50, (255,0,0), cv2.FILLED, cv2.LINE_AA)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### 사각형 그리기
* rectangle(이미지객체, (왼쪽위x, 왼쪽위y), (오른쪽아래x, 오른쪽아래y), 색깔, 두께)로 사각형을 그립니다.
* rectangle(이미지객체, (왼쪽위x, 왼쪽위y), (오른쪽아래x, 오른쪽아래y), 색깔, cv2.FILLED)로 색칠한 사각형을 그립니다.

In [26]:
img[:] = (0,0,0)
cv2.rectangle(img, (10,10), (190,190), (255,0,0), 2)
cv2.rectangle(img, (210,210), (390,390), (255,0,0), cv2.FILLED)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### 글자 나타내기
* putText(이미지객체, '글자', (x, y), 폰트, 크기, 색깔, 굵기)로 글자를 나타냅니다.
* OpenCV에서 사용하는 대표적인 글꼴 종류
    * cv2.FONT_HERSHEY_SIMPLEX : 보통 크기의 산 세리프 글꼴
    * cv2.FONT_HERSHEY_SCRIPT_SIMPLEX : 필기체

In [33]:
img[:] = (0,0,0)
cv2.putText(img, 'python', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 1)
cv2.imshow('img', img) 
cv2.waitKey(0)
cv2.destroyAllWindows()